# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: mochi

before:
  hooks:
    - go mod tidy

builds:
  - id: mochi
    main: ./cmd/mochi/main.go
    binary: mochi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.gitCommit={{ .Commit }}
      - -X main.buildTime={{ .Date }}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - VERSION

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: mochilang
    name: mochi

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
